window.esdocSearchIndex = [
  [
    "faunadb/src/asyncstream.js~asyncstream",
    "class/src/AsyncStream.js~AsyncStream.html",
    "<span>AsyncStream</span> <span class=\"search-result-import-path\">faunadb/src/AsyncStream.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~badrequest",
    "class/src/errors.js~BadRequest.html",
    "<span>BadRequest</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/builtin.js~builtin",
    "class/src/model/Builtin.js~Builtin.html",
    "<span>Builtin</span> <span class=\"search-result-import-path\">faunadb/src/model/Builtin.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/builtin.js~class",
    "class/src/model/Builtin.js~Class.html",
    "<span>Class</span> <span class=\"search-result-import-path\">faunadb/src/model/Builtin.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/builtin.js~classindex",
    "class/src/model/Builtin.js~ClassIndex.html",
    "<span>ClassIndex</span> <span class=\"search-result-import-path\">faunadb/src/model/Builtin.js</span>",
    "class"
  ],
  [
    "faunadb/src/client.js~client",
    "class/src/Client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">faunadb/src/Client.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/codec.js~codec",
    "class/src/model/Codec.js~Codec.html",
    "<span>Codec</span> <span class=\"search-result-import-path\">faunadb/src/model/Codec.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/builtin.js~database",
    "class/src/model/Builtin.js~Database.html",
    "<span>Database</span> <span class=\"search-result-import-path\">faunadb/src/model/Builtin.js</span>",
    "class"
  ],
  [
    "faunadb/src/objects.js~event",
    "class/src/objects.js~Event.html",
    "<span>Event</span> <span class=\"search-result-import-path\">faunadb/src/objects.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~faunaerror",
    "class/src/errors.js~FaunaError.html",
    "<span>FaunaError</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~faunahttperror",
    "class/src/errors.js~FaunaHTTPError.html",
    "<span>FaunaHTTPError</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/objects.js~faunaset",
    "class/src/objects.js~FaunaSet.html",
    "<span>FaunaSet</span> <span class=\"search-result-import-path\">faunadb/src/objects.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/field.js~field",
    "class/src/model/Field.js~Field.html",
    "<span>Field</span> <span class=\"search-result-import-path\">faunadb/src/model/Field.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/builtin.js~index",
    "class/src/model/Builtin.js~Index.html",
    "<span>Index</span> <span class=\"search-result-import-path\">faunadb/src/model/Builtin.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~internalerror",
    "class/src/errors.js~InternalError.html",
    "<span>InternalError</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~invalidquery",
    "class/src/errors.js~InvalidQuery.html",
    "<span>InvalidQuery</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~invalidvalue",
    "class/src/errors.js~InvalidValue.html",
    "<span>InvalidValue</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/builtin.js~key",
    "class/src/model/Builtin.js~Key.html",
    "<span>Key</span> <span class=\"search-result-import-path\">faunadb/src/model/Builtin.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~methodnotallowed",
    "class/src/errors.js~MethodNotAllowed.html",
    "<span>MethodNotAllowed</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/model.js~model",
    "class/src/model/Model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">faunadb/src/model/Model.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~notfound",
    "class/src/errors.js~NotFound.html",
    "<span>NotFound</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/objects.js~page",
    "class/src/objects.js~Page.html",
    "<span>Page</span> <span class=\"search-result-import-path\">faunadb/src/objects.js</span>",
    "class"
  ],
  [
    "faunadb/src/pagestream.js~pagestream",
    "class/src/PageStream.js~PageStream.html",
    "<span>PageStream</span> <span class=\"search-result-import-path\">faunadb/src/PageStream.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~permissiondenied",
    "class/src/errors.js~PermissionDenied.html",
    "<span>PermissionDenied</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/objects.js~ref",
    "class/src/objects.js~Ref.html",
    "<span>Ref</span> <span class=\"search-result-import-path\">faunadb/src/objects.js</span>",
    "class"
  ],
  [
    "faunadb/src/model/codec.js~refcodec",
    "variable/index.html#static-variable-RefCodec",
    "<span>RefCodec</span> <span class=\"search-result-import-path\">faunadb/src/model/Codec.js</span>",
    "variable"
  ],
  [
    "faunadb/src/errors.js~unauthorized",
    "class/src/errors.js~Unauthorized.html",
    "<span>Unauthorized</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/errors.js~unavailableerror",
    "class/src/errors.js~UnavailableError.html",
    "<span>UnavailableError</span> <span class=\"search-result-import-path\">faunadb/src/errors.js</span>",
    "class"
  ],
  [
    "faunadb/src/query.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~concat",
    "function/index.html#static-function-concat",
    "<span>concat</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~contains",
    "function/index.html#static-function-contains",
    "<span>contains</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~count",
    "function/index.html#static-function-count",
    "<span>count</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~delete_expr",
    "function/index.html#static-function-delete_expr",
    "<span>delete_expr</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~difference",
    "function/index.html#static-function-difference",
    "<span>difference</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~divide",
    "function/index.html#static-function-divide",
    "<span>divide</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~do_expr",
    "function/index.html#static-function-do_expr",
    "<span>do_expr</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~equals",
    "function/index.html#static-function-equals",
    "<span>equals</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~exists",
    "function/index.html#static-function-exists",
    "<span>exists</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~foreach",
    "function/index.html#static-function-foreach",
    "<span>foreach</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~get",
    "function/index.html#static-function-get",
    "<span>get</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~if_expr",
    "function/index.html#static-function-if_expr",
    "<span>if_expr</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~intersection",
    "function/index.html#static-function-intersection",
    "<span>intersection</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~join",
    "function/index.html#static-function-join",
    "<span>join</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~lambda",
    "function/index.html#static-function-lambda",
    "<span>lambda</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~lambda_expr",
    "function/index.html#static-function-lambda_expr",
    "<span>lambda_expr</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~let_expr",
    "function/index.html#static-function-let_expr",
    "<span>let_expr</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~match",
    "function/index.html#static-function-match",
    "<span>match</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~multiply",
    "function/index.html#static-function-multiply",
    "<span>multiply</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~object",
    "function/index.html#static-function-object",
    "<span>object</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~paginate",
    "function/index.html#static-function-paginate",
    "<span>paginate</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~quote",
    "function/index.html#static-function-quote",
    "<span>quote</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~replace",
    "function/index.html#static-function-replace",
    "<span>replace</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~select",
    "function/index.html#static-function-select",
    "<span>select</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~selectwithdefault",
    "function/index.html#static-function-selectWithDefault",
    "<span>selectWithDefault</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~subtract",
    "function/index.html#static-function-subtract",
    "<span>subtract</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~union",
    "function/index.html#static-function-union",
    "<span>union</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~update",
    "function/index.html#static-function-update",
    "<span>update</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "faunadb/src/query.js~variable",
    "function/index.html#static-function-variable",
    "<span>variable</span> <span class=\"search-result-import-path\">faunadb/src/query.js</span>",
    "function"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber11",
    "Builtin",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber58",
    "Builtin class",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber139",
    "Builtin class index",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber50",
    "Builtin custom field",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber18",
    "Builtin database",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber37",
    "Builtin database existence",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber71",
    "Builtin index",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber42",
    "Builtin key",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber85",
    "Builtin terms and values",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber124",
    "Builtin unique index",
    "test"
  ],
  [
    "",
    "test-file/test/model/builtin_test.js.html#lineNumber103",
    "Builtin values",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber9",
    "Client",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber58",
    "Client delete",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber31",
    "Client get",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber14",
    "Client invalid key",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber64",
    "Client logger",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber76",
    "Client logger_no_auth",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber51",
    "Client patch",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber19",
    "Client ping",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber36",
    "Client post",
    "test"
  ],
  [
    "",
    "test-file/test/client_test.js.html#lineNumber40",
    "Client put",
    "test"
  ],
  [
    "",
    "test-file/test/model/codec_test.js.html#lineNumber12",
    "Codec",
    "test"
  ],
  [
    "",
    "test-file/test/model/codec_test.js.html#lineNumber55",
    "Codec custom codec",
    "test"
  ],
  [
    "",
    "test-file/test/model/codec_test.js.html#lineNumber36",
    "Codec model fields",
    "test"
  ],
  [
    "",
    "test-file/test/model/codec_test.js.html#lineNumber49",
    "Codec no codec",
    "test"
  ],
  [
    "",
    "test-file/test/model/codec_test.js.html#lineNumber64",
    "Codec ref codec",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber11",
    "Model",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber47",
    "Model bad field",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber18",
    "Model common fields",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber25",
    "Model persistence",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber97",
    "Model ref, id, ts",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber51",
    "Model replace",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber79",
    "Model replace with new fields",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber128",
    "Model stream",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber144",
    "Model toString",
    "test"
  ],
  [
    "",
    "test-file/test/model/model_test.js.html#lineNumber116",
    "Model update",
    "test"
  ],
  [
    "",
    "test-file/test/model/util_test.js.html#lineNumber4",
    "model/_util",
    "test"
  ],
  [
    "",
    "test-file/test/model/util_test.js.html#lineNumber23",
    "model/_util diff",
    "test"
  ],
  [
    "",
    "test-file/test/model/util_test.js.html#lineNumber5",
    "model/_util dup",
    "test"
  ],
  [
    "",
    "test-file/test/model/util_test.js.html#lineNumber12",
    "model/_util getPath",
    "test"
  ],
  [
    "",
    "test-file/test/model/util_test.js.html#lineNumber17",
    "model/_util setPath",
    "test"
  ],
  [
    "",
    "test-file/test/objects_test.js.html#lineNumber7",
    "objects",
    "test"
  ],
  [
    "",
    "test-file/test/objects_test.js.html#lineNumber42",
    "objects event",
    "test"
  ],
  [
    "",
    "test-file/test/objects_test.js.html#lineNumber48",
    "objects page",
    "test"
  ],
  [
    "",
    "test-file/test/objects_test.js.html#lineNumber12",
    "objects ref",
    "test"
  ],
  [
    "",
    "test-file/test/objects_test.js.html#lineNumber32",
    "objects set",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber9",
    "query",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber224",
    "query add",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber198",
    "query concat",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber203",
    "query contains",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber122",
    "query count",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber130",
    "query create",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber149",
    "query delete",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber167",
    "query difference",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber240",
    "query divide",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber41",
    "query do",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber191",
    "query equals",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber115",
    "query exists",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber90",
    "query foreach",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber98",
    "query get",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber36",
    "query if",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber163",
    "query intersection",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber171",
    "query join",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber57",
    "query lambda",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber32",
    "query let/var",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber80",
    "query map",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber155",
    "query match",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber229",
    "query multiply",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber47",
    "query object",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber103",
    "query paginate",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber52",
    "query quote",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber143",
    "query replace",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber210",
    "query select",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber218",
    "query select for array",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber234",
    "query subtract",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber159",
    "query union",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber137",
    "query update",
    "test"
  ],
  [
    "",
    "test-file/test/query_test.js.html#lineNumber248",
    "query varargs",
    "test"
  ],
  [
    "src/asyncstream.js",
    "file/src/AsyncStream.js.html",
    "src/AsyncStream.js",
    "file"
  ],
  [
    "src/asyncstream.js~asyncstream#all",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-all",
    "src/AsyncStream.js~AsyncStream#all",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream#each",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-each",
    "src/AsyncStream.js~AsyncStream#each",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream#filter",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-filter",
    "src/AsyncStream.js~AsyncStream#filter",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream#flatmap",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-flatMap",
    "src/AsyncStream.js~AsyncStream#flatMap",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream#flatten",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-flatten",
    "src/AsyncStream.js~AsyncStream#flatten",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream#map",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-map",
    "src/AsyncStream.js~AsyncStream#map",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream#next",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-next",
    "src/AsyncStream.js~AsyncStream#next",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream#takewhile",
    "class/src/AsyncStream.js~AsyncStream.html#instance-method-takeWhile",
    "src/AsyncStream.js~AsyncStream#takeWhile",
    "method"
  ],
  [
    "src/asyncstream.js~asyncstream.fromiterable",
    "class/src/AsyncStream.js~AsyncStream.html#static-method-fromIterable",
    "src/AsyncStream.js~AsyncStream.fromIterable",
    "method"
  ],
  [
    "src/client.js",
    "file/src/Client.js.html",
    "src/Client.js",
    "file"
  ],
  [
    "src/client.js~client#constructor",
    "class/src/Client.js~Client.html#instance-constructor-constructor",
    "src/Client.js~Client#constructor",
    "method"
  ],
  [
    "src/client.js~client#delete",
    "class/src/Client.js~Client.html#instance-method-delete",
    "src/Client.js~Client#delete",
    "method"
  ],
  [
    "src/client.js~client#get",
    "class/src/Client.js~Client.html#instance-method-get",
    "src/Client.js~Client#get",
    "method"
  ],
  [
    "src/client.js~client#patch",
    "class/src/Client.js~Client.html#instance-method-patch",
    "src/Client.js~Client#patch",
    "method"
  ],
  [
    "src/client.js~client#ping",
    "class/src/Client.js~Client.html#instance-method-ping",
    "src/Client.js~Client#ping",
    "method"
  ],
  [
    "src/client.js~client#post",
    "class/src/Client.js~Client.html#instance-method-post",
    "src/Client.js~Client#post",
    "method"
  ],
  [
    "src/client.js~client#put",
    "class/src/Client.js~Client.html#instance-method-put",
    "src/Client.js~Client#put",
    "method"
  ],
  [
    "src/client.js~client#query",
    "class/src/Client.js~Client.html#instance-method-query",
    "src/Client.js~Client#query",
    "method"
  ],
  [
    "src/pagestream.js",
    "file/src/PageStream.js.html",
    "src/PageStream.js",
    "file"
  ],
  [
    "src/pagestream.js~pagestream#constructor",
    "class/src/PageStream.js~PageStream.html#instance-constructor-constructor",
    "src/PageStream.js~PageStream#constructor",
    "method"
  ],
  [
    "src/pagestream.js~pagestream#next",
    "class/src/PageStream.js~PageStream.html#instance-method-next",
    "src/PageStream.js~PageStream#next",
    "method"
  ],
  [
    "src/pagestream.js~pagestream.elements",
    "class/src/PageStream.js~PageStream.html#static-method-elements",
    "src/PageStream.js~PageStream.elements",
    "method"
  ],
  [
    "src/errors.js",
    "file/src/errors.js.html",
    "src/errors.js",
    "file"
  ],
  [
    "src/errors.js~faunaerror#constructor",
    "class/src/errors.js~FaunaError.html#instance-constructor-constructor",
    "src/errors.js~FaunaError#constructor",
    "method"
  ],
  [
    "src/errors.js~faunaerror#message",
    "class/src/errors.js~FaunaError.html#instance-member-message",
    "src/errors.js~FaunaError#message",
    "member"
  ],
  [
    "src/errors.js~faunaerror#stack",
    "class/src/errors.js~FaunaError.html#instance-member-stack",
    "src/errors.js~FaunaError#stack",
    "member"
  ],
  [
    "src/errors.js~faunahttperror#constructor",
    "class/src/errors.js~FaunaHTTPError.html#instance-constructor-constructor",
    "src/errors.js~FaunaHTTPError#constructor",
    "method"
  ],
  [
    "src/errors.js~faunahttperror#errors",
    "class/src/errors.js~FaunaHTTPError.html#instance-member-errors",
    "src/errors.js~FaunaHTTPError#errors",
    "member"
  ],
  [
    "src/errors.js~faunahttperror#parameters",
    "class/src/errors.js~FaunaHTTPError.html#instance-member-parameters",
    "src/errors.js~FaunaHTTPError#parameters",
    "member"
  ],
  [
    "src/errors.js~faunahttperror#reason",
    "class/src/errors.js~FaunaHTTPError.html#instance-member-reason",
    "src/errors.js~FaunaHTTPError#reason",
    "member"
  ],
  [
    "src/model/builtin.js",
    "file/src/model/Builtin.js.html",
    "src/model/Builtin.js",
    "file"
  ],
  [
    "src/model/builtin.js~builtin.classref",
    "class/src/model/Builtin.js~Builtin.html#static-member-classRef",
    "src/model/Builtin.js~Builtin.classRef",
    "member"
  ],
  [
    "src/model/builtin.js~class.createformodel",
    "class/src/model/Builtin.js~Class.html#static-method-createForModel",
    "src/model/Builtin.js~Class.createForModel",
    "method"
  ],
  [
    "src/model/builtin.js~class.getformodel",
    "class/src/model/Builtin.js~Class.html#static-method-getForModel",
    "src/model/Builtin.js~Class.getForModel",
    "method"
  ],
  [
    "src/model/builtin.js~classindex#match",
    "class/src/model/Builtin.js~ClassIndex.html#instance-method-match",
    "src/model/Builtin.js~ClassIndex#match",
    "method"
  ],
  [
    "src/model/builtin.js~classindex.createformodel",
    "class/src/model/Builtin.js~ClassIndex.html#static-method-createForModel",
    "src/model/Builtin.js~ClassIndex.createForModel",
    "method"
  ],
  [
    "src/model/builtin.js~classindex.getformodel",
    "class/src/model/Builtin.js~ClassIndex.html#static-method-getForModel",
    "src/model/Builtin.js~ClassIndex.getForModel",
    "method"
  ],
  [
    "src/model/builtin.js~index#getsingle",
    "class/src/model/Builtin.js~Index.html#instance-method-getSingle",
    "src/model/Builtin.js~Index#getSingle",
    "method"
  ],
  [
    "src/model/builtin.js~index#match",
    "class/src/model/Builtin.js~Index.html#instance-method-match",
    "src/model/Builtin.js~Index#match",
    "method"
  ],
  [
    "src/model/builtin.js~index.createformodel",
    "class/src/model/Builtin.js~Index.html#static-method-createForModel",
    "src/model/Builtin.js~Index.createForModel",
    "method"
  ],
  [
    "src/model/codec.js",
    "file/src/model/Codec.js.html",
    "src/model/Codec.js",
    "file"
  ],
  [
    "src/model/codec.js~codec#decode",
    "class/src/model/Codec.js~Codec.html#instance-method-decode",
    "src/model/Codec.js~Codec#decode",
    "method"
  ],
  [
    "src/model/codec.js~codec#encode",
    "class/src/model/Codec.js~Codec.html#instance-method-encode",
    "src/model/Codec.js~Codec#encode",
    "method"
  ],
  [
    "src/model/field.js",
    "file/src/model/Field.js.html",
    "src/model/Field.js",
    "file"
  ],
  [
    "src/model/field.js~field#constructor",
    "class/src/model/Field.js~Field.html#instance-constructor-constructor",
    "src/model/Field.js~Field#constructor",
    "method"
  ],
  [
    "src/model/model.js",
    "file/src/model/Model.js.html",
    "src/model/Model.js",
    "file"
  ],
  [
    "src/model/model.js~model#client",
    "class/src/model/Model.js~Model.html#instance-member-client",
    "src/model/Model.js~Model#client",
    "member"
  ],
  [
    "src/model/model.js~model#constructor",
    "class/src/model/Model.js~Model.html#instance-constructor-constructor",
    "src/model/Model.js~Model#constructor",
    "method"
  ],
  [
    "src/model/model.js~model#createquery",
    "class/src/model/Model.js~Model.html#instance-method-createQuery",
    "src/model/Model.js~Model#createQuery",
    "method"
  ],
  [
    "src/model/model.js~model#delete",
    "class/src/model/Model.js~Model.html#instance-method-delete",
    "src/model/Model.js~Model#delete",
    "method"
  ],
  [
    "src/model/model.js~model#deletequery",
    "class/src/model/Model.js~Model.html#instance-method-deleteQuery",
    "src/model/Model.js~Model#deleteQuery",
    "method"
  ],
  [
    "src/model/model.js~model#getencoded",
    "class/src/model/Model.js~Model.html#instance-method-getEncoded",
    "src/model/Model.js~Model#getEncoded",
    "method"
  ],
  [
    "src/model/model.js~model#id",
    "class/src/model/Model.js~Model.html#instance-get-id",
    "src/model/Model.js~Model#id",
    "member"
  ],
  [
    "src/model/model.js~model#isnewinstance",
    "class/src/model/Model.js~Model.html#instance-method-isNewInstance",
    "src/model/Model.js~Model#isNewInstance",
    "method"
  ],
  [
    "src/model/model.js~model#ref",
    "class/src/model/Model.js~Model.html#instance-get-ref",
    "src/model/Model.js~Model#ref",
    "member"
  ],
  [
    "src/model/model.js~model#replacequery",
    "class/src/model/Model.js~Model.html#instance-method-replaceQuery",
    "src/model/Model.js~Model#replaceQuery",
    "method"
  ],
  [
    "src/model/model.js~model#save",
    "class/src/model/Model.js~Model.html#instance-method-save",
    "src/model/Model.js~Model#save",
    "method"
  ],
  [
    "src/model/model.js~model#savequery",
    "class/src/model/Model.js~Model.html#instance-method-saveQuery",
    "src/model/Model.js~Model#saveQuery",
    "method"
  ],
  [
    "src/model/model.js~model#ts",
    "class/src/model/Model.js~Model.html#instance-get-ts",
    "src/model/Model.js~Model#ts",
    "member"
  ],
  [
    "src/model/model.js~model#updatequery",
    "class/src/model/Model.js~Model.html#instance-method-updateQuery",
    "src/model/Model.js~Model#updateQuery",
    "method"
  ],
  [
    "src/model/model.js~model.addfield",
    "class/src/model/Model.js~Model.html#static-method-addField",
    "src/model/Model.js~Model.addField",
    "method"
  ],
  [
    "src/model/model.js~model.classref",
    "class/src/model/Model.js~Model.html#static-member-classRef",
    "src/model/Model.js~Model.classRef",
    "member"
  ],
  [
    "src/model/model.js~model.create",
    "class/src/model/Model.js~Model.html#static-method-create",
    "src/model/Model.js~Model.create",
    "method"
  ],
  [
    "src/model/model.js~model.faunaclassname",
    "class/src/model/Model.js~Model.html#static-member-faunaClassName",
    "src/model/Model.js~Model.faunaClassName",
    "member"
  ],
  [
    "src/model/model.js~model.fields",
    "class/src/model/Model.js~Model.html#static-member-fields",
    "src/model/Model.js~Model.fields",
    "member"
  ],
  [
    "src/model/model.js~model.get",
    "class/src/model/Model.js~Model.html#static-method-get",
    "src/model/Model.js~Model.get",
    "method"
  ],
  [
    "src/model/model.js~model.getbyid",
    "class/src/model/Model.js~Model.html#static-method-getById",
    "src/model/Model.js~Model.getById",
    "method"
  ],
  [
    "src/model/model.js~model.getfromindex",
    "class/src/model/Model.js~Model.html#static-method-getFromIndex",
    "src/model/Model.js~Model.getFromIndex",
    "method"
  ],
  [
    "src/model/model.js~model.getfromresource",
    "class/src/model/Model.js~Model.html#static-method-getFromResource",
    "src/model/Model.js~Model.getFromResource",
    "method"
  ],
  [
    "src/model/model.js~model.isabstract",
    "class/src/model/Model.js~Model.html#static-method-isAbstract",
    "src/model/Model.js~Model.isAbstract",
    "method"
  ],
  [
    "src/model/model.js~model.page",
    "class/src/model/Model.js~Model.html#static-method-page",
    "src/model/Model.js~Model.page",
    "method"
  ],
  [
    "src/model/model.js~model.pageindex",
    "class/src/model/Model.js~Model.html#static-method-pageIndex",
    "src/model/Model.js~Model.pageIndex",
    "method"
  ],
  [
    "src/model/model.js~model.setup",
    "class/src/model/Model.js~Model.html#static-method-setup",
    "src/model/Model.js~Model.setup",
    "method"
  ],
  [
    "src/model/model.js~model.stream",
    "class/src/model/Model.js~Model.html#static-method-stream",
    "src/model/Model.js~Model.stream",
    "method"
  ],
  [
    "src/model/model.js~model.streamindex",
    "class/src/model/Model.js~Model.html#static-method-streamIndex",
    "src/model/Model.js~Model.streamIndex",
    "method"
  ],
  [
    "src/objects.js",
    "file/src/objects.js.html",
    "src/objects.js",
    "file"
  ],
  [
    "src/objects.js~event#action",
    "class/src/objects.js~Event.html#instance-member-action",
    "src/objects.js~Event#action",
    "member"
  ],
  [
    "src/objects.js~event#constructor",
    "class/src/objects.js~Event.html#instance-constructor-constructor",
    "src/objects.js~Event#constructor",
    "method"
  ],
  [
    "src/objects.js~event#resource",
    "class/src/objects.js~Event.html#instance-member-resource",
    "src/objects.js~Event#resource",
    "member"
  ],
  [
    "src/objects.js~event#ts",
    "class/src/objects.js~Event.html#instance-member-ts",
    "src/objects.js~Event#ts",
    "member"
  ],
  [
    "src/objects.js~event.fromraw",
    "class/src/objects.js~Event.html#static-method-fromRaw",
    "src/objects.js~Event.fromRaw",
    "method"
  ],
  [
    "src/objects.js~faunaset#constructor",
    "class/src/objects.js~FaunaSet.html#instance-constructor-constructor",
    "src/objects.js~FaunaSet#constructor",
    "method"
  ],
  [
    "src/objects.js~faunaset#query",
    "class/src/objects.js~FaunaSet.html#instance-member-query",
    "src/objects.js~FaunaSet#query",
    "member"
  ],
  [
    "src/objects.js~page#after",
    "class/src/objects.js~Page.html#instance-member-after",
    "src/objects.js~Page#after",
    "member"
  ],
  [
    "src/objects.js~page#before",
    "class/src/objects.js~Page.html#instance-member-before",
    "src/objects.js~Page#before",
    "member"
  ],
  [
    "src/objects.js~page#constructor",
    "class/src/objects.js~Page.html#instance-constructor-constructor",
    "src/objects.js~Page#constructor",
    "method"
  ],
  [
    "src/objects.js~page#data",
    "class/src/objects.js~Page.html#instance-member-data",
    "src/objects.js~Page#data",
    "member"
  ],
  [
    "src/objects.js~page#mapdata",
    "class/src/objects.js~Page.html#instance-method-mapData",
    "src/objects.js~Page#mapData",
    "method"
  ],
  [
    "src/objects.js~page.fromraw",
    "class/src/objects.js~Page.html#static-method-fromRaw",
    "src/objects.js~Page.fromRaw",
    "method"
  ],
  [
    "src/objects.js~ref#class",
    "class/src/objects.js~Ref.html#instance-get-class",
    "src/objects.js~Ref#class",
    "member"
  ],
  [
    "src/objects.js~ref#constructor",
    "class/src/objects.js~Ref.html#instance-constructor-constructor",
    "src/objects.js~Ref#constructor",
    "method"
  ],
  [
    "src/objects.js~ref#equals",
    "class/src/objects.js~Ref.html#instance-method-equals",
    "src/objects.js~Ref#equals",
    "method"
  ],
  [
    "src/objects.js~ref#id",
    "class/src/objects.js~Ref.html#instance-get-id",
    "src/objects.js~Ref#id",
    "member"
  ],
  [
    "src/objects.js~ref#value",
    "class/src/objects.js~Ref.html#instance-member-value",
    "src/objects.js~Ref#value",
    "member"
  ],
  [
    "src/query.js",
    "file/src/query.js.html",
    "src/query.js",
    "file"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber10",
    "stream",
    "test"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber19",
    "stream filter",
    "test"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber33",
    "stream flatMap",
    "test"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber27",
    "stream flatten",
    "test"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber15",
    "stream map",
    "test"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber39",
    "stream page stream",
    "test"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber11",
    "stream stream",
    "test"
  ],
  [
    "",
    "test-file/test/stream_test.js.html#lineNumber23",
    "stream takeWhile",
    "test"
  ],
  [
    "test/client_test.js",
    "test-file/test/client_test.js.html",
    "test/client_test.js",
    "testFile"
  ],
  [
    "test/model/builtin_test.js",
    "test-file/test/model/builtin_test.js.html",
    "test/model/builtin_test.js",
    "testFile"
  ],
  [
    "test/model/codec_test.js",
    "test-file/test/model/codec_test.js.html",
    "test/model/codec_test.js",
    "testFile"
  ],
  [
    "test/model/model_test.js",
    "test-file/test/model/model_test.js.html",
    "test/model/model_test.js",
    "testFile"
  ],
  [
    "test/model/util_test.js",
    "test-file/test/model/util_test.js.html",
    "test/model/util_test.js",
    "testFile"
  ],
  [
    "test/objects_test.js",
    "test-file/test/objects_test.js.html",
    "test/objects_test.js",
    "testFile"
  ],
  [
    "test/query_test.js",
    "test-file/test/query_test.js.html",
    "test/query_test.js",
    "testFile"
  ],
  [
    "test/stream_test.js",
    "test-file/test/stream_test.js.html",
    "test/stream_test.js",
    "testFile"
  ]
]